apiVersion: v1
kind: LimitRange
metadata:
  name: limit
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "250Mi"
    defaultRequest:
      cpu: "500m"
      memory: "128Mi"
    type: Container
